### ISSUE TITLE
Finish settings page

### ISSUE THREAD

**Issue by marzavec** [hack-chat/hackchat-client#12]
Currently the settings page is just a placeholder. This page of course will have all the client settings. I would go into more detail, but it's kind of self-explanatory.

This issue is dependent of getting the local storage issue resolved, as the settings will be loaded and saved to local storage.

I would like to add in settings for the main menu button position and LTR options, along with the usual nick, password, color, etc settings.

**Comment by KnowsCount** [comment]
by 

> usual nick, password,

do you refer to allowing the users to set default username and password so that they can be auto-filled when joining or creating channels?

**Comment by marzavec** [comment]
Yep, that is exactly it- much like how this is done with the current client.

**Comment by KnowsCount** [comment]
can you provide me with a more specific description of what should be on the settings page? I imagine I could help.

**Comment by marzavec** [comment]
Sorry for the late reply. The `settings` route will contain the ui elements needed to alter the client UI, user data, client behavior and (possibly) network settings.

### User data
- Name (string input)
- Password (password input)
- Color (rgb wheel)
- Remember Channels (checkbox)

### UI
- Theme (dropdown)
- Allow Katex (checkbox)
- Katex Granular Controls (collapse + checkboxes)
- Allow Markdown (checkbox)
- Markdown Granular Controls (collapse + checkboxes/dropdowns)
- Language (dropdown)
- Display Users (checkbox)
- Display Channels (checkbox)
- LTR mode (checkbox)
- Menu Position (left/right)
- Highlight Mentions (checkbox)

### Behaviour
- Allow Notifications (checkbox)
- Audio Notifications (checkbox)
- Auto Reconnect (checkbox)

### Network
- Target Server (dropdown/text input)

This list is in no particular order and the grouping is arguable. The network option is just an idea atm, a way to bring distributed functionality in. There are likely some that I'm forgetting tbh- I'll check my notes when I'm able and update this thread if needed

**Comment by marzavec** [comment]
Completed with 9eccc06a6b6a28d3acd9afc7e546cbf30fca04cd
