### ISSUE TITLE
KaTeX support!

### ISSUE THREAD

**Issue by marzavec** [hack-chat/hackchat-client#18]
This will be an easy one, I just haven't had time to get around to it.

The katex renderer will piggy-back off the [remarkable renderer](https://github.com/hack-chat/hackchat-client/blob/master/app/containers/ChatManager/index.js#L34) (as it does in the legacy build)~~, however the current remarkable renderer should be placed into it's own component before this happens~~

Edit: stricken changes have been made with d4a258f9c481444cc4fbaf755d3b8f8651018794

**Comment by KnowsCount** [comment]
is it tbd in the same way as the [prior version](https://github.com/hack-chat/main/tree/master/client/vendor)?

**Comment by marzavec** [comment]
I'm not sure what you mean by "the same way". The Katex lib will be added to the package.json, then included in the rendering component, the remarkable renderer will then be told to use an instance of Katex. The way a user posts Latex to the chat will remain the same.

**Comment by marzavec** [comment]
Feature added with c78648c7d1c3fbbe97d6972dfb5257480fdf51e9 and is live on beta.hack.chat
