### ISSUE TITLE
Implement local storage handling

### ISSUE THREAD

**Issue by marzavec** [hack-chat/hackchat-client#19]
Local storage should be used to save the users nick and password, along with other settings ( #12 ). This data should be [loaded](https://github.com/hack-chat/hackchat-client/blob/master/app/app.js#L27) into the redux store when the app starts. This may also tie into #6

**Comment by henrywright** [comment]
The data in local storage could be accessed by different users if the computer is shared. How can we ensure the sensitive portion of the stored data is cleared when a user is finished using hack.chat?

**Comment by marzavec** [comment]
I have seen this concern raised a few times in the past, because this is the same behavior that the legacy client uses. There are very few options available to address the concern. Do you have any suggestions?

**Comment by henrywright** [comment]
In my opinion I wouldn't store sensitive information in local storage but if the legacy client does this currently then we could implement a clearing mechanism to ensure the data is deleted 

The data could automatically deleted when the user closes hack.chat or alternatively a button could be provided for the user to click. I'm not sure which approach is best. What are your thoughts?

**Comment by marzavec** [comment]
With 317173ea2eddbfec4bf12a5e734c848acd47d1f3 all settings are cached to local storage and loaded into redux on startup.
