### ISSUE TITLE
Don't translate the GUI by google 

### ISSUE THREAD

**Issue by Potato32** [hack-chat/hackchat-client#2]
From what i feel , you want multi-language UI in the new client beta.hack.chat and decide to not hire a real translator ,
if you want. i can translate the text in chinese , if you can gave me a sheet to match

**Comment by marzavec** [comment]
The new client source has been released, you can find the Chinese [translations here](https://github.com/hack-chat/hackchat-client/blob/master/app/translations/zh.json)
