### ISSUE TITLE
Edge on windows shows a blank page

### ISSUE THREAD

**Issue by KnowsCount** [hack-chat/hackchat-client#29]
I basically ran `npm start` and everything works absolutely fine on macOS/Windows Chrome and macOS Safari, however, things went wrong when one of my friend is visiting the local network (ip:3000) version using Windows Edge browser. 
I do not currently have detail information but is it a problem with Edge?

**Comment by marzavec** [comment]
Without more info I'm not sure, I've just tried it on `Version 87.0.664.60 (Official build) (64-bit)` and had no problems. . .

![https://i.imgur.com/rWNqor7.png](https://i.imgur.com/rWNqor7.png)

**Comment by KnowsCount** [comment]
ermm.. is it because the two friends of mine did not use `localhost`?– They visited using LAN. But it worked fine with other people who used Chrome on Windows.

**Comment by KnowsCount** [comment]
I'll close it for now.

**Comment by marzavec** [comment]
Some more info might help, if they send over their terminal logs or edge console logs I might be able to assist
