### ISSUE TITLE
volunteering full translation to Spanish of hack.chat

### ISSUE THREAD

**Issue by ghost** [hack-chat/hackchat-client#34]
hello there, I'd like to volunteer to translate the site @ hack.chat and/or beta.hack.chat. I am not a developer, though, but I understand a bit about coding ,but I am unfamiliar with current programming languages. I tried to open a pull request, but I got lost. I am also new to this site. Any guidance from anyone?
Thanks!

**Comment by marzavec** [comment]
@DarkEagleHere Hello. I've transferred this issue into the `hackchat-client` repository, as it is the only one that supports multiple languages. You'll first need to fork this project, then modify the files that @KnowsCount mentioned, then create a [pull request](https://docs.github.com/es/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request).

@KnowsCount Thanks :D

**Comment by KnowsCount** [comment]
you're welcome. just doing what I can do.

**Comment by marzavec** [comment]
Closing due to literal ghosting
